name: Digital Local Laws
title: Digital Local Laws Project
org: University at Albany and NYS Department of State
base_url: ''
profiles:
  production:
    base_url: https://digital-local-laws.github.io
    deploy:
      host: github_pages
      branch: master
